# Generated by Django 5.1.6 on 2025-02-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_jobcategory_application_notes_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
